name: Bot Poll (commands)

on:
  workflow_dispatch:  # manuell starten im Actions-Tab

permissions:
  contents: write

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install requests

      - name: Run bot_poll once
        run: python bot_poll.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Persist last_update_id
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot_poll: persist last_update_id"
          file_pattern: last_update_id.txt
