name: Status Now
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install requests
      - name: Send snapshot (force)
        run: python telegram_send.py --force
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update signal_state (status-now)"
          file_pattern: signal_state.json
