name: Status now

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install --upgrade requests pandas numpy ta

      - name: Generate (no cooldown)
        env:
          COOLDOWN_MINUTES: "0"
        run: python -u generate_message.py

      - name: Send
        env:
          TELEGRAM_TOKEN:         ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID:       ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_ALERT_CHAT_ID: ${{ secrets.TELEGRAM_ALERT_CHAT_ID }}
        run: python -u telegram_send.py
